---
- name: test
  hosts: all
  become: yes
  become_user: docker
  gather_facts: yes

  tasks:


  

  - name: Minio new MW for test
    docker_container:
     name: minio
     image: minio/minio:RELEASE.2022-06-30T20-58-09Z
     restart_policy: always
     command: server --console-address ":9001" /minio/data
     state: started
     #restart: yes
     volumes:
       - s3data:/minio/data
     ports:
       - "{{ MINIO_PORT_API }}:9000"
       - "{{MINIO_PORT_DASHBOARD}}:9001"
     exposed_ports:
       - "9000"
       - "9001"
     env:
        MINIO_ROOT_USER: "{{S3_USER}}"
        MINIO_ROOT_PASSWORD: "{{S3_PASSWORD}}"

    
