- name: Install docker SDK for python
  hosts: all
  become: true
  tasks:


   - name: Pip install RedHat
     package:
        name: 
           - python3
           - python3-pip
           - python-setuptools   #problem  Failed to import the required Python library (setuptools) on localhost.localdomain's Python /usr/bin/python
        state: present

   - name: install module docker for python
     pip:
        name: docker
        executable: pip3

     
  
     
     
     
   
   

   